#%RAML 1.0 DataType


type: array
items:
    type: object
    properties:
      employeeId:
        type: integer
        required: true
      firstNamne:
        type: string
        required: false
      lastNamne: 
        type: string
        required: false
      age:
        type: integer
        required: false
      gender:
        type: string
        required: false
      bloodGroup:
        type: string
        required: false
      email:
        type: string
        required: false
      phoneNumber:
        type: string
        required: false



